<a href="https://colab.research.google.com/github/MariaNatiele/Edtudos_DataScience/blob/main/Numpay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Formação ciência de dados

#Numpy é um biblioteca de analise de dados

In [ ]:
import numpy as np

In [ ]:

#criando arry com definição de tipo
array = np.array([15,6,9,8,7], dtype=np.int32)
array2 = np.array([15,6,9,8,7], dtype=np.float64)

In [ ]:
array, array2

(array([15,  6,  9,  8,  7], dtype=int32), array([15.,  6.,  9.,  8.,  7.]))

In [ ]:
#Matriz bidimensional
matriz = np.array([[5,6,3],[18,25,66],[14,7,21]])

In [ ]:
matriz

array([[ 5,  6,  3],
       [18, 25, 66],
       [14,  7, 21]])

In [ ]:
aleatorio = np.random.random((5))
aleatorio

array([0.08561607, 0.80058586, 0.51966951, 0.16192452, 0.15455636])

In [ ]:
#numero aleatorio com sementes no numpy
semente = np.random.default_rng(2)
ale = semente.random(5)
print(ale)
print("------------------------------------------------------------------")
alet = semente.integers(10, size=(2,3))
print(alet)

[0.26161213 0.29849114 0.81422574 0.09191594 0.60010053]
------------------------------------------------------------------
[[8 7 9]
 [1 8 0]]


In [ ]:
#removendo repetição
dados3 = np.array([1,5,9,8,7,4,1,2,5,5,6,3,6,25])
dados3 = np.unique(dados3)
dados3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 25])

#Funções Númericas

In [ ]:
print('Max',dados3.max())
print('Min',dados3.min())
print('Sum',dados3.sum())
print('Media',dados3.mean())
print('STD -> desvio Padrão: ',dados3.std())

Max 25
Min 1
Sum 70
Media 7.0
STD -> desvio Padrão:  6.48074069840786


##Extração de elementos

In [ ]:
m = np.array([1,5,8,10,36,28])
print(m[1:2])
print('-----------------------------')
print(m[0:3])

[5]
-----------------------------
[1 5 8]


#Pandas 

In [ ]:
import pandas as pd

In [ ]:
#Carregando dados
dados = pd.read_csv("Popular_Baby_Names.csv")

In [ ]:
dados.head()

Year of Birth  Gender Ethnicity Child's First Name  Count  Rank
0           2011  FEMALE  HISPANIC          GERALDINE     13    75
1           2011  FEMALE  HISPANIC                GIA     21    67
2           2011  FEMALE  HISPANIC             GIANNA     49    42
3           2011  FEMALE  HISPANIC            GISELLE     38    51
4           2011  FEMALE  HISPANIC              GRACE     36    53

In [ ]:
print("Linhas e colunas",dados.shape)
print("-----------------------------------------------")
print("ultimas linhas",dados.tail(2))

Linhas e colunas (49509, 6)
-----------------------------------------------
ultimas linhas        Year of Birth  Gender           Ethnicity Child's First Name  Count  \
49507           2018  FEMALE  BLACK NON HISPANIC             Simone     10   
49508           2018  FEMALE  BLACK NON HISPANIC              Zahra     10   

       Rank  
49507    40  
49508    40  


In [ ]:
#descrição dos dados
dados.describe()

Year of Birth         Count          Rank
count   49509.000000  49509.000000  49509.000000
mean     2013.407421     33.839807     57.032418
std         2.145505     38.877785     25.504754
min      2011.000000     10.000000      1.000000
25%      2012.000000     13.000000     38.000000
50%      2013.000000     20.000000     58.000000
75%      2014.000000     36.000000     78.000000
max      2019.000000    426.000000    102.000000

In [ ]:
#mostrar só uma coluna
dados.columns
dados[["Child's First Name"]]

Child's First Name
0              GERALDINE
1                    GIA
2                 GIANNA
3                GISELLE
4                  GRACE
...                  ...
49504               Nala
49505            Royalty
49506            Sariyah
49507             Simone
49508              Zahra

[49509 rows x 1 columns]

#Modulos e Pacotes

#Statistics 
https://docs.python.org/pt-br/3/library/statistics.html

In [ ]:
import statistics as es


In [ ]:
conjunto = [1,25,8,6,9,7,4,6,10]
a = es.mean(conjunto)
b = es.median(conjunto)
c = es.mode(conjunto)
print(a)
print("Median",b)
print("Mode",c)

8.444444444444445
Median 7
Mode 6


#Função

In [ ]:
def minhafuncao(num):
    return num * 2
print("Retorno da Função ",minhafuncao(12))


1. Faca um programa que tenha uma função chamada Amplitude. A função deve receber uma lista e imprimir a amplitude. Cire também um código para testar a função

2. Faça uma função que receba ua string e imprima esta stringna forma vertical 
P
y
t
h
o
n
Uma String funciona como uma lista.

3. Crie um programa que leia o peso de uma carga em números inteiros . Se o peso fro até 10kg, informe que o valor será de 50. Entre 11 e 20, informe que o valor será de 80. Se for maior de 20 informe que o transporte não é aceito,

In [ ]:
#função chamada Amplitude
def Amplitude(valor):
  m = max(valor)
  n = min(valor)
  return m - n

lista = [25,6,9,8,7,10,2]
print(Amplitude(lista))


In [ ]:
#string e imprima na vertical
def funct(nome):
  num = len(nome)
  for i in range(1,num):
    print(nome[i])


funct("Maria")

a
r
i
a


In [ ]:
#Crie um programa que leia o peso de uma carga em números inteiros . Se o peso fro até 10kg, informe que o  Entre 11 e 20,
# informe que . Se for maior de 20 informe que ,

def conta(valor):
  if valor <=10 : 
    print("valor será de 50.")
  elif valor == 11 or valor <= 20:
    print("o valor será de 80")
  if valor > 20 :
    print("o transporte não é aceito")



conta(25)


o transporte não é aceito


#Limpeza e Tratamento de Dados